#! /bin/sh

sxhkd &
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload example &
  done
else
  polybar --reload example &
fi
feh --bg-fill ~/Pictures/wallpaper.jpg

bspc monitor DP-0 -d I II III IV V
bspc monitor DVI-D-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config focus_follows_pointer          true
bspc config pointer_follows_focus           true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
